export const countryCodes = {
  British: "GB",
  German: "DE",
  French: "FR",
  Italian: "IT",
  Spanish: "ES",
  Australian: "AU",
  Dutch: "NL",
  Belgian: "BE",
  Brazilian: "BR",
  Canadian: "CA",
  Finnish: "FI",
  Mexican: "MX",
  Japanese: "JP",
  Danish: "DK",
  Austrian: "AT",
  Swiss: "CH",
  Swedish: "SE",
  Portuguese: "PT",
  American: "US",
  Russian: "RU",
  Indian: "IN",
  Chinese: "CN",
  Argentinian: "AR",
  "South African": "ZA",
  "New Zealander": "NZ",
  Thai: "TH",
  Vietnamese: "VN",
  Polish: "PL",
  Turkish: "TR",
  Monegasque: "MC",
  
  UK: "GB",
  Germany: "DE",
  France: "FR",
  Italy: "IT",
  Spain: "ES",
  Australia: "AU",
  Netherlands: "NL",
  Belgium: "BE",
  Brazil: "BR",
  Canada: "CA",
  Finland: "FI",
  Mexico: "MX",
  Japan: "JP",
  Denmark: "DK",
  Austria: "AT",
  Switzerland: "CH",
  Sweden: "SE",
  Portugal: "PT",
  USA: "US",
  Hungary: "HU",
  UAE: "AE",
  Qatar: "QA",
  Bahrain: "BH",
  "Saudi Arabia": "SA",
  Singapore: "SG",
  Azerbaijan: "AZ",
  Russia: "RU",
  India: "IN",
  China: "CN",
  Argentina: "AR",
  "South Africa": "ZA",
  "New Zealand": "NZ",
  Thailand: "TH",
  Vietnam: "VN",
  Poland: "PL",
  Turkey: "TR",
  Monaco: "MC",
};

export function getFlagImg(nameOrNationality) {
  const code = countryCodes[nameOrNationality];
  if (!code) return null;
  return `https://flagcdn.com/24x18/${code.toLowerCase()}.png`;
}
